### ISSUE TITLE
New data for Stan model

### ISSUE THREAD

**Issue by Pozdniakov** [paul-buerkner/thurstonianIRT#12]
Hi, Paul! 

Is it possible to use new data for fitted model via Stan? I've found only coefficients for individual scores in the output object.

**Comment by paul-buerkner** [comment]
Can you clarify your question a little bit. What new data due you have in mind?

**Comment by Pozdniakov** [comment]
I've prepared and fitted a dataset to the model. If I use `predict()` function I get the scores. However, I can't find a way to use the model to predict scores on new respondents using the same model (and the same data structure). It seems to be possible with lavaan model (using parameter `newdata =` in `predict()` method for lavaan object. However, lavaan fitting leads to performance issues on my data (37 blocks x 4 ranks(= 6 comparisons) on 16 traits, 10k raws).

**Comment by paul-buerkner** [comment]
I see. I am afraid this is not yet possible and also conceptually hard to do in a fully Bayesian manner. I have to think what would be a consistent way to do it and if it is reasonably possible.

**Comment by IanEisenberg** [comment]
I'm also interested in estimating trait scores for new data. Ideally while fixing the item parameters and only estimating new participants trait scores. This is different than the predict function - we'd want to use the estimated item lambda values and apply them to new responses.

**Comment by Pozdniakov** [comment]
> I'm also interested in estimating trait scores for new data. Ideally while fixing the item parameters and only estimating new participants trait scores. This is different than the predict function - we'd want to use the estimated item lambda values and apply them to new responses.

Oh, I didn't know that there is a difference. Is this difference substantial?

**Comment by IanEisenberg** [comment]
I believe what the model does right now is jointly estimate lambda parameters (the loadings of each item on each trait, assuming no cross-loadings - that is, each item is associated with only one trait),  the correlation matrix of the traits, as well as the traits themselves (and other things).

Below are the parameters I took out of a model I created. You can see all these different parameters.

```
parameters {
  // item thresholds depend on the family
  vector[family == 1 || family == 3 || family == 4 ? N_itemC : 0] gamma;
  ordered[ncat - 1] gamma_ord[family == 2 ? N_itemC : 0];
  vector<lower=0>[N_item_pos] lambda_pos;  // item loadings
  vector<upper=0>[N_item_neg] lambda_neg;  // item loadings
  vector<lower=0>[N_item_est] psi_est;  // estimated item SDs
  // unscaled group level effects of traits within persons
  matrix[N_trait, N_person] z_trait;
  // cholesky factor of correlation matrix of traits
  cholesky_factor_corr[N_trait] L_trait;
  vector[N_item] z;  // unscaled random effects
  // dispersion parameter of the beta family
  // TODO: make comparison specific?
  vector<lower=0>[family == 4 ? 1 : 0] disp;
}
```

Typically you'd want to estimate all of the item level parameters (the lambda parameters, etc.) on some large dataset, and then use the estimated parameters to estimate trait level values for new data. If you re-estimate the entire model each time you (1) spend a bunch of time fitting which slows down performance vs just getting the trait level scores and (2) end up with different item parameters each time you score. Not to mention the desire to assess the performance of the model out of sample.

It seems there should be a way to separate item estimation from person-trait estimation. But I am just learning stan and bayesian modeling in general so not sure. I'm thinking creating a new model, where the fixed parameters are passed as data instead of a parameter would maybe work.

**Comment by paul-buerkner** [comment]
The canonical way would indeed be fixing the item parameters and only estimating the person parameters. Such a feature should be a valuable addition to this package I think.

**Comment by IanEisenberg** [comment]
I have created another stan model where I can pass the fit lambda, psi, gamma, r and L_trait parameters. This leaves only the eta parameters to be fit (I believe). It seems to work well at recovering eta parameters from an out-of-sample test set.

I've made a few helper functions to take the fitted model and create a new prediction model using the new `prediction.stan` model.

I'm honestly not very familiar with R package design, but happy to add these files to a branch and you can see them/use them as you see fit.

**Comment by paul-buerkner** [comment]
This is nice! I would very much appreciate a PR for the functionality you built even if I need to polish it a little afterwards before we can officially include it in the package.

**Comment by bozhang3** [comment]
> I'm also interested in estimating trait scores for new data. Ideally while fixing the item parameters and only estimating new participants trait scores. This is different than the predict function - we'd want to use the estimated item lambda values and apply them to new responses.

Hi @IanEisenberg, I just want to double check with you to see whether it is true that the predict function involves re-estimation of the model every time we supply new data. I am currently trying to score a small number of new observations based in item parameters estimated from a large sample.  I used lavaan to estimate item parameters and used the predict function to score new observations. I thought I was doing what I thought until I saw your comments. Do you know some ways to do what I want to do?

**Comment by paul-buerkner** [comment]
Predictions for new data is now possible for Stan models via argument `newdata` in the predict method.
