### ISSUE TITLE
fitting models in lavaan doesn't seem to work

### ISSUE THREAD

**Issue by tomfaulkenberry** [paul-buerkner/thurstonianIRT#3]
Using the "triplets" data from the documentation, I get the following error:

```
> fit <- fit_TIRT_lavaan(triplets_long)
Warning message:
In lav_model_estimate(lavmodel = lavmodel, lavpartable = lavpartable,  :
  lavaan WARNING: the optimizer warns that a solution has NOT been found!
```

This error appears for both the CRAN version as well as the developer version. 

Note that using `fit_TIRT_stan` works fine.

**Comment by paul-buerkner** [comment]
Thanks! The subset of the original data that I used for the example `triplets` data set turned out to be too small so that lavaan ran into convergence issues. I extended the example data from 100 to 200 participants and now lavaan seems to converge nicely. Can you confirm with the latest dev version of the package?

**Comment by tomfaulkenberry** [comment]
Excellent...yes, everything works as claimed now, so I am closing the issue.  I appreciate the quick work, Paul!
